version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    container_name: laravel_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ride_hailing
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    image: nginx:stable
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mariadb_data:
